config/routes.rb
Rails.application.routes.draw do

  scope path: 'ventas' do

    get "service-worker.js", to: "service_worker#service_worker", defaults: { format: :js }

    get "manifest.json",
        to: "service_worker#manifest",
        defaults: { format: :json }

    root 'home#index', as: 'home'



    scope :pausa, module: :pausa, as: :pausa do
      get "manifest.json",     to: "service_worker#manifest",      defaults: { format: :json }
      get "service-worker.js", to: "service_worker#service_worker", defaults: { format: :js }
      root "home#index"
      namespace :api, defaults: { format: :json } do
        namespace :v1 do
          post "login", to: "sessions#create"
          get :notify, to: "utils#notify"
          resources :app_users do
            collection do
              get :pending
              get :me
            end
            member do
              patch :approve
              patch :push_token
              patch :active, to: "app_users#set_active"
            end
          end
          post :login, to: "sessions#create"
          resources :pause_windows, param: :id, only: [:index, :update]
          resources :banners, only: [:index]
          resources :holidays, only: [] do
            collection do
              get :between
            end
          end
          resources :daily_logs, only: [] do
            collection do
              get  :today
              patch :mark
            end
          end

          # recordatorios/notificaciones
          resources :reminders, only: [] do
            collection do
              post :trigger
              post :opened
            end
          end

          # reportes
          resources :reports, only: [] do
            collection do
              get :pausas
            end
          end

        end
      end

    end




    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    namespace :authentication, path: '', as: '' do
      resources :users, path: '/users' do
        member do
          get :manage_permisos
          patch :update_permisos
        end
      end
      resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
    end




    resources :users, only: :show, path: '/user', param: :username, as: 'perfil'


    resources :records, only: [:index], path: '/records' do

    end





  end


end

app/views/shared/_flash.html.erb
<%= turbo_frame_tag 'flash' do %>
  <% if alert %>
    <%= javascript_tag do %>
      Swal.fire({
      icon: 'error',
      title: 'Error',
      text: '<%= j alert %>',
      confirmButtonText: 'OK'
      });
    <% end %>
  <% elsif notice %>
    <div class="max-w-lg mx-auto mt-4 p-4 bg-green-100 border border-green-400 text-green-700 rounded">
      <h2 class="text-center font-bold"><%= notice %></h2>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<div class="mt-4">

  <div class="bg-gray-800 w-full border-b border-gray-700 relative">
    <div class="flex items-center justify-center p-4">

      <button
        data-controller="theme"
        data-action="click->theme#toggle"
        class="absolute left-4 p-2 rounded-full
               bg-gray-200 hover:bg-gray-300
               dark:bg-slate-700 dark:hover:bg-slate-600">
        <span data-theme-target="icon">🌙</span>
      </button>

      <%= link_to raw('<svg class="h-5 w-5 text-blue-600 inline-block mr-2 align-middle" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg>Home'), home_path,
                  class: "text-xl font-bold text-blue-600 hover:text-blue-500 transition" %>


      <% if Current.user %>
        <div class="absolute right-4 flex items-center gap-6">
          <%= link_to 'Usuario',
                      perfil_path(Current.user.username),
                      class: "text-green-500 hover:text-green-700" %>

          <%= link_to 'Cerrar sesión',
                      session_path(Current.user.id),
                      class: "text-lg text-red-600 hover:text-red-500 transition",
                      data: {
                        controller: "logout-confirmation",
                        action: "click->logout-confirmation#deleteSession",
                        "logout-confirmation-redirect-url-value": new_session_path
                      } %>
        </div>
      <% end %>
    </div>
  </div>
</div>